name: Deploy to Local Kubernetes

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Step 3: Set up Kubernetes credentials
      - name: Set up Kubernetes credentials
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      # Debugging Step 4: Check if ~/.ssh already exists
      - name: Check if ~/.ssh exists
        run: |
          echo "Checking if ~/.ssh directory exists"
          ls -ld ~/.ssh

      # Step 4: Set up SSH key
      - name: Set up SSH
        run: |
          echo "Creating SSH directory"
          mkdir -p ~/.ssh
          echo "Verifying if SSH directory was created"
          ls -ld ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.0.131 >> ~/.ssh/known_hosts
          ssh-keyscan -H 192.168.0.132 >> ~/.ssh/known_hosts
          ssh-keyscan -H 192.168.0.133 >> ~/.ssh/known_hosts

      # Step 5: Create Kubernetes resources
      - name: Deploy index.html to Kubernetes
        run: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:alpine
                  volumeMounts:
                  - name: index-volume
                    mountPath: /usr/share/nginx/html/index.html
                    subPath: index.html
          ---
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: index-configmap
          data:
            index.html: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>Hello World - NGINX</title>
              </head>
              <body>
                  <h1>Hello, World!</h1>
              </body>
              </html>
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
          spec:
            type: NodePort
            selector:
              app: nginx
            ports:
              - port: 80
                targetPort: 80
                nodePort: 30001
          " > deployment.yaml
          
          # Apply the Kubernetes resources
          kubectl apply -f deployment.yaml

      # Step 6: Verify the deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc


