name: Deploy to Internal Network

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # This will use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Your setup commands here
          sudo apt-get update
          sudo apt-get install -y kubectl
          
      - name: Set up Kubernetes credentials
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy Application
        run: |
          kubectl apply -f deployment.yaml
